# version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: totalk_db
    environment:
      POSTGRES_USER: totalkadmin
      POSTGRES_PASSWORD: mishashopa
      POSTGRES_DB: totalk_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U totalkadmin totalk_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 