CREATE TABLE IF NOT EXISTS events (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slots INTEGER NOT NULL,
    selected_slots INTEGER NOT NULL DEFAULT 0,
    tag_name VARCHAR(255) NOT NULL,
    time TIMESTAMP NOT NULL,
    in_queue INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
); 