// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/event.proto

package gen_event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Статусы очереди
type QueueStatus int32

const (
	QueueStatus_QUEUE_STATUS_UNSPECIFIED QueueStatus = 0
	QueueStatus_QUEUE_STATUS_WAITING     QueueStatus = 1
	QueueStatus_QUEUE_STATUS_ACTIVE      QueueStatus = 2
	QueueStatus_QUEUE_STATUS_COMPLETED   QueueStatus = 3
	QueueStatus_QUEUE_STATUS_CANCELLED   QueueStatus = 4
)

// Enum value maps for QueueStatus.
var (
	QueueStatus_name = map[int32]string{
		0: "QUEUE_STATUS_UNSPECIFIED",
		1: "QUEUE_STATUS_WAITING",
		2: "QUEUE_STATUS_ACTIVE",
		3: "QUEUE_STATUS_COMPLETED",
		4: "QUEUE_STATUS_CANCELLED",
	}
	QueueStatus_value = map[string]int32{
		"QUEUE_STATUS_UNSPECIFIED": 0,
		"QUEUE_STATUS_WAITING":     1,
		"QUEUE_STATUS_ACTIVE":      2,
		"QUEUE_STATUS_COMPLETED":   3,
		"QUEUE_STATUS_CANCELLED":   4,
	}
)

func (x QueueStatus) Enum() *QueueStatus {
	p := new(QueueStatus)
	*p = x
	return p
}

func (x QueueStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_event_proto_enumTypes[0].Descriptor()
}

func (QueueStatus) Type() protoreflect.EnumType {
	return &file_proto_event_proto_enumTypes[0]
}

func (x QueueStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueStatus.Descriptor instead.
func (QueueStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{0}
}

// Запрос на обработку события
type ProcessEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEventRequest) Reset() {
	*x = ProcessEventRequest{}
	mi := &file_proto_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEventRequest) ProtoMessage() {}

func (x *ProcessEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEventRequest.ProtoReflect.Descriptor instead.
func (*ProcessEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessEventRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProcessEventRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ProcessEventRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Ответ на обработку события
type ProcessEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEventResponse) Reset() {
	*x = ProcessEventResponse{}
	mi := &file_proto_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEventResponse) ProtoMessage() {}

func (x *ProcessEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEventResponse.ProtoReflect.Descriptor instead.
func (*ProcessEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessEventResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessEventResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Запрос на получение статуса события
type GetEventStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventStatusRequest) Reset() {
	*x = GetEventStatusRequest{}
	mi := &file_proto_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventStatusRequest) ProtoMessage() {}

func (x *GetEventStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventStatusRequest.ProtoReflect.Descriptor instead.
func (*GetEventStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Ответ с статусом события
type GetEventStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventStatusResponse) Reset() {
	*x = GetEventStatusResponse{}
	mi := &file_proto_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventStatusResponse) ProtoMessage() {}

func (x *GetEventStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventStatusResponse.ProtoReflect.Descriptor instead.
func (*GetEventStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetEventStatusResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetEventStatusResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetEventStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetEventStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetEventStatusResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Запись в очереди событий
type EventQueue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventQueue) Reset() {
	*x = EventQueue{}
	mi := &file_proto_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventQueue) ProtoMessage() {}

func (x *EventQueue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventQueue.ProtoReflect.Descriptor instead.
func (*EventQueue) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{4}
}

func (x *EventQueue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventQueue) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventQueue) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventQueue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventQueue) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *EventQueue) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EventQueue) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Запрос на добавление в очередь
type JoinQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinQueueRequest) Reset() {
	*x = JoinQueueRequest{}
	mi := &file_proto_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQueueRequest) ProtoMessage() {}

func (x *JoinQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQueueRequest.ProtoReflect.Descriptor instead.
func (*JoinQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{5}
}

func (x *JoinQueueRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *JoinQueueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Ответ на добавление в очередь
type JoinQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinQueueResponse) Reset() {
	*x = JoinQueueResponse{}
	mi := &file_proto_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQueueResponse) ProtoMessage() {}

func (x *JoinQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQueueResponse.ProtoReflect.Descriptor instead.
func (*JoinQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{6}
}

func (x *JoinQueueResponse) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

func (x *JoinQueueResponse) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

// Запрос на выход из очереди
type LeaveQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveQueueRequest) Reset() {
	*x = LeaveQueueRequest{}
	mi := &file_proto_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveQueueRequest) ProtoMessage() {}

func (x *LeaveQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveQueueRequest.ProtoReflect.Descriptor instead.
func (*LeaveQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveQueueRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *LeaveQueueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Ответ на выход из очереди
type LeaveQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveQueueResponse) Reset() {
	*x = LeaveQueueResponse{}
	mi := &file_proto_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveQueueResponse) ProtoMessage() {}

func (x *LeaveQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveQueueResponse.ProtoReflect.Descriptor instead.
func (*LeaveQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveQueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на получение статуса очереди
type GetQueueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatusRequest) Reset() {
	*x = GetQueueStatusRequest{}
	mi := &file_proto_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatusRequest) ProtoMessage() {}

func (x *GetQueueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatusRequest.ProtoReflect.Descriptor instead.
func (*GetQueueStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{9}
}

func (x *GetQueueStatusRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// Ответ с статусом очереди
type GetQueueStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queues        []*EventQueue          `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatusResponse) Reset() {
	*x = GetQueueStatusResponse{}
	mi := &file_proto_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatusResponse) ProtoMessage() {}

func (x *GetQueueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatusResponse.ProtoReflect.Descriptor instead.
func (*GetQueueStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{10}
}

func (x *GetQueueStatusResponse) GetQueues() []*EventQueue {
	if x != nil {
		return x.Queues
	}
	return nil
}

// Запрос на получение позиции пользователя
type GetUserPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPositionRequest) Reset() {
	*x = GetUserPositionRequest{}
	mi := &file_proto_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPositionRequest) ProtoMessage() {}

func (x *GetUserPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPositionRequest.ProtoReflect.Descriptor instead.
func (*GetUserPositionRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserPositionRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetUserPositionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Ответ с позицией пользователя
type GetUserPositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int32                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPositionResponse) Reset() {
	*x = GetUserPositionResponse{}
	mi := &file_proto_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPositionResponse) ProtoMessage() {}

func (x *GetUserPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPositionResponse.ProtoReflect.Descriptor instead.
func (*GetUserPositionResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserPositionResponse) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

// Запрос на обработку следующего в очереди
type ProcessNextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessNextRequest) Reset() {
	*x = ProcessNextRequest{}
	mi := &file_proto_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessNextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessNextRequest) ProtoMessage() {}

func (x *ProcessNextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessNextRequest.ProtoReflect.Descriptor instead.
func (*ProcessNextRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{13}
}

func (x *ProcessNextRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// Ответ на обработку следующего в очереди
type ProcessNextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *EventQueue            `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessNextResponse) Reset() {
	*x = ProcessNextResponse{}
	mi := &file_proto_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessNextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessNextResponse) ProtoMessage() {}

func (x *ProcessNextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessNextResponse.ProtoReflect.Descriptor instead.
func (*ProcessNextResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessNextResponse) GetQueue() *EventQueue {
	if x != nil {
		return x.Queue
	}
	return nil
}

// Запрос на закрытие очереди
type CloseQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseQueueRequest) Reset() {
	*x = CloseQueueRequest{}
	mi := &file_proto_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseQueueRequest) ProtoMessage() {}

func (x *CloseQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseQueueRequest.ProtoReflect.Descriptor instead.
func (*CloseQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{15}
}

func (x *CloseQueueRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// Ответ на закрытие очереди
type CloseQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseQueueResponse) Reset() {
	*x = CloseQueueResponse{}
	mi := &file_proto_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseQueueResponse) ProtoMessage() {}

func (x *CloseQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseQueueResponse.ProtoReflect.Descriptor instead.
func (*CloseQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{16}
}

func (x *CloseQueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_event_proto protoreflect.FileDescriptor

const file_proto_event_proto_rawDesc = "" +
	"\n" +
	"\x11proto/event.proto\x12\tgen_event\"[\n" +
	"\x13ProcessEventRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\">\n" +
	"\x14ProcessEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"'\n" +
	"\x15GetEventStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xaa\x01\n" +
	"\x16GetEventStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xc2\x01\n" +
	"\n" +
	"EventQueue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"F\n" +
	"\x10JoinQueueRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"J\n" +
	"\x11JoinQueueResponse\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\"G\n" +
	"\x11LeaveQueueRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\".\n" +
	"\x12LeaveQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x15GetQueueStatusRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"G\n" +
	"\x16GetQueueStatusResponse\x12-\n" +
	"\x06queues\x18\x01 \x03(\v2\x15.gen_event.EventQueueR\x06queues\"L\n" +
	"\x16GetUserPositionRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"5\n" +
	"\x17GetUserPositionResponse\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bposition\"/\n" +
	"\x12ProcessNextRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"B\n" +
	"\x13ProcessNextResponse\x12+\n" +
	"\x05queue\x18\x01 \x01(\v2\x15.gen_event.EventQueueR\x05queue\".\n" +
	"\x11CloseQueueRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\".\n" +
	"\x12CloseQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\x96\x01\n" +
	"\vQueueStatus\x12\x1c\n" +
	"\x18QUEUE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14QUEUE_STATUS_WAITING\x10\x01\x12\x17\n" +
	"\x13QUEUE_STATUS_ACTIVE\x10\x02\x12\x1a\n" +
	"\x16QUEUE_STATUS_COMPLETED\x10\x03\x12\x1a\n" +
	"\x16QUEUE_STATUS_CANCELLED\x10\x042\xb6\x01\n" +
	"\fEventService\x12O\n" +
	"\fProcessEvent\x12\x1e.gen_event.ProcessEventRequest\x1a\x1f.gen_event.ProcessEventResponse\x12U\n" +
	"\x0eGetEventStatus\x12 .gen_event.GetEventStatusRequest\x1a!.gen_event.GetEventStatusResponse2\xf0\x03\n" +
	"\x11EventQueueService\x12F\n" +
	"\tJoinQueue\x12\x1b.gen_event.JoinQueueRequest\x1a\x1c.gen_event.JoinQueueResponse\x12I\n" +
	"\n" +
	"LeaveQueue\x12\x1c.gen_event.LeaveQueueRequest\x1a\x1d.gen_event.LeaveQueueResponse\x12U\n" +
	"\x0eGetQueueStatus\x12 .gen_event.GetQueueStatusRequest\x1a!.gen_event.GetQueueStatusResponse\x12X\n" +
	"\x0fGetUserPosition\x12!.gen_event.GetUserPositionRequest\x1a\".gen_event.GetUserPositionResponse\x12L\n" +
	"\vProcessNext\x12\x1d.gen_event.ProcessNextRequest\x1a\x1e.gen_event.ProcessNextResponse\x12I\n" +
	"\n" +
	"CloseQueue\x12\x1c.gen_event.CloseQueueRequest\x1a\x1d.gen_event.CloseQueueResponseB\rZ\v./gen_eventb\x06proto3"

var (
	file_proto_event_proto_rawDescOnce sync.Once
	file_proto_event_proto_rawDescData []byte
)

func file_proto_event_proto_rawDescGZIP() []byte {
	file_proto_event_proto_rawDescOnce.Do(func() {
		file_proto_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_event_proto_rawDesc), len(file_proto_event_proto_rawDesc)))
	})
	return file_proto_event_proto_rawDescData
}

var file_proto_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_event_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_event_proto_goTypes = []any{
	(QueueStatus)(0),                // 0: gen_event.QueueStatus
	(*ProcessEventRequest)(nil),     // 1: gen_event.ProcessEventRequest
	(*ProcessEventResponse)(nil),    // 2: gen_event.ProcessEventResponse
	(*GetEventStatusRequest)(nil),   // 3: gen_event.GetEventStatusRequest
	(*GetEventStatusResponse)(nil),  // 4: gen_event.GetEventStatusResponse
	(*EventQueue)(nil),              // 5: gen_event.EventQueue
	(*JoinQueueRequest)(nil),        // 6: gen_event.JoinQueueRequest
	(*JoinQueueResponse)(nil),       // 7: gen_event.JoinQueueResponse
	(*LeaveQueueRequest)(nil),       // 8: gen_event.LeaveQueueRequest
	(*LeaveQueueResponse)(nil),      // 9: gen_event.LeaveQueueResponse
	(*GetQueueStatusRequest)(nil),   // 10: gen_event.GetQueueStatusRequest
	(*GetQueueStatusResponse)(nil),  // 11: gen_event.GetQueueStatusResponse
	(*GetUserPositionRequest)(nil),  // 12: gen_event.GetUserPositionRequest
	(*GetUserPositionResponse)(nil), // 13: gen_event.GetUserPositionResponse
	(*ProcessNextRequest)(nil),      // 14: gen_event.ProcessNextRequest
	(*ProcessNextResponse)(nil),     // 15: gen_event.ProcessNextResponse
	(*CloseQueueRequest)(nil),       // 16: gen_event.CloseQueueRequest
	(*CloseQueueResponse)(nil),      // 17: gen_event.CloseQueueResponse
}
var file_proto_event_proto_depIdxs = []int32{
	5,  // 0: gen_event.GetQueueStatusResponse.queues:type_name -> gen_event.EventQueue
	5,  // 1: gen_event.ProcessNextResponse.queue:type_name -> gen_event.EventQueue
	1,  // 2: gen_event.EventService.ProcessEvent:input_type -> gen_event.ProcessEventRequest
	3,  // 3: gen_event.EventService.GetEventStatus:input_type -> gen_event.GetEventStatusRequest
	6,  // 4: gen_event.EventQueueService.JoinQueue:input_type -> gen_event.JoinQueueRequest
	8,  // 5: gen_event.EventQueueService.LeaveQueue:input_type -> gen_event.LeaveQueueRequest
	10, // 6: gen_event.EventQueueService.GetQueueStatus:input_type -> gen_event.GetQueueStatusRequest
	12, // 7: gen_event.EventQueueService.GetUserPosition:input_type -> gen_event.GetUserPositionRequest
	14, // 8: gen_event.EventQueueService.ProcessNext:input_type -> gen_event.ProcessNextRequest
	16, // 9: gen_event.EventQueueService.CloseQueue:input_type -> gen_event.CloseQueueRequest
	2,  // 10: gen_event.EventService.ProcessEvent:output_type -> gen_event.ProcessEventResponse
	4,  // 11: gen_event.EventService.GetEventStatus:output_type -> gen_event.GetEventStatusResponse
	7,  // 12: gen_event.EventQueueService.JoinQueue:output_type -> gen_event.JoinQueueResponse
	9,  // 13: gen_event.EventQueueService.LeaveQueue:output_type -> gen_event.LeaveQueueResponse
	11, // 14: gen_event.EventQueueService.GetQueueStatus:output_type -> gen_event.GetQueueStatusResponse
	13, // 15: gen_event.EventQueueService.GetUserPosition:output_type -> gen_event.GetUserPositionResponse
	15, // 16: gen_event.EventQueueService.ProcessNext:output_type -> gen_event.ProcessNextResponse
	17, // 17: gen_event.EventQueueService.CloseQueue:output_type -> gen_event.CloseQueueResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_event_proto_init() }
func file_proto_event_proto_init() {
	if File_proto_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_event_proto_rawDesc), len(file_proto_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_event_proto_goTypes,
		DependencyIndexes: file_proto_event_proto_depIdxs,
		EnumInfos:         file_proto_event_proto_enumTypes,
		MessageInfos:      file_proto_event_proto_msgTypes,
	}.Build()
	File_proto_event_proto = out.File
	file_proto_event_proto_goTypes = nil
	file_proto_event_proto_depIdxs = nil
}
