// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: notify/internal/domain/proto/notification.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_notify_internal_domain_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_internal_domain_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notify_internal_domain_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendNotificationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SendNotificationRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_notify_internal_domain_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_internal_domain_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notify_internal_domain_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNotificationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationStatusRequest) Reset() {
	*x = GetNotificationStatusRequest{}
	mi := &file_notify_internal_domain_proto_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationStatusRequest) ProtoMessage() {}

func (x *GetNotificationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_internal_domain_proto_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationStatusRequest) Descriptor() ([]byte, []int) {
	return file_notify_internal_domain_proto_notification_proto_rawDescGZIP(), []int{2}
}

func (x *GetNotificationStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNotificationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationStatusResponse) Reset() {
	*x = GetNotificationStatusResponse{}
	mi := &file_notify_internal_domain_proto_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationStatusResponse) ProtoMessage() {}

func (x *GetNotificationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_internal_domain_proto_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationStatusResponse) Descriptor() ([]byte, []int) {
	return file_notify_internal_domain_proto_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotificationStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetNotificationStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_notify_internal_domain_proto_notification_proto protoreflect.FileDescriptor

const file_notify_internal_domain_proto_notification_proto_rawDesc = "" +
	"\n" +
	"/notify/internal/domain/proto/notification.proto\x12\fnotification\"G\n" +
	"\x17SendNotificationRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"*\n" +
	"\x18SendNotificationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x1cGetNotificationStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x1dGetNotificationStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xea\x01\n" +
	"\x13NotificationService\x12a\n" +
	"\x10SendNotification\x12%.notification.SendNotificationRequest\x1a&.notification.SendNotificationResponse\x12p\n" +
	"\x15GetNotificationStatus\x12*.notification.GetNotificationStatusRequest\x1a+.notification.GetNotificationStatusResponseB\x1eZ\x1cnotify/internal/domain/protob\x06proto3"

var (
	file_notify_internal_domain_proto_notification_proto_rawDescOnce sync.Once
	file_notify_internal_domain_proto_notification_proto_rawDescData []byte
)

func file_notify_internal_domain_proto_notification_proto_rawDescGZIP() []byte {
	file_notify_internal_domain_proto_notification_proto_rawDescOnce.Do(func() {
		file_notify_internal_domain_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notify_internal_domain_proto_notification_proto_rawDesc), len(file_notify_internal_domain_proto_notification_proto_rawDesc)))
	})
	return file_notify_internal_domain_proto_notification_proto_rawDescData
}

var file_notify_internal_domain_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notify_internal_domain_proto_notification_proto_goTypes = []any{
	(*SendNotificationRequest)(nil),       // 0: notification.SendNotificationRequest
	(*SendNotificationResponse)(nil),      // 1: notification.SendNotificationResponse
	(*GetNotificationStatusRequest)(nil),  // 2: notification.GetNotificationStatusRequest
	(*GetNotificationStatusResponse)(nil), // 3: notification.GetNotificationStatusResponse
}
var file_notify_internal_domain_proto_notification_proto_depIdxs = []int32{
	0, // 0: notification.NotificationService.SendNotification:input_type -> notification.SendNotificationRequest
	2, // 1: notification.NotificationService.GetNotificationStatus:input_type -> notification.GetNotificationStatusRequest
	1, // 2: notification.NotificationService.SendNotification:output_type -> notification.SendNotificationResponse
	3, // 3: notification.NotificationService.GetNotificationStatus:output_type -> notification.GetNotificationStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notify_internal_domain_proto_notification_proto_init() }
func file_notify_internal_domain_proto_notification_proto_init() {
	if File_notify_internal_domain_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notify_internal_domain_proto_notification_proto_rawDesc), len(file_notify_internal_domain_proto_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notify_internal_domain_proto_notification_proto_goTypes,
		DependencyIndexes: file_notify_internal_domain_proto_notification_proto_depIdxs,
		MessageInfos:      file_notify_internal_domain_proto_notification_proto_msgTypes,
	}.Build()
	File_notify_internal_domain_proto_notification_proto = out.File
	file_notify_internal_domain_proto_notification_proto_goTypes = nil
	file_notify_internal_domain_proto_notification_proto_depIdxs = nil
}
