server:
  port: 8080

kafka:
  brokers:
    - localhost:9092
  group_id: notification-service
  topics:
    notifications: notifications

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: notifications 